### ISSUE TITLE
Docs & v1

### ISSUE THREAD

**Issue by clarkeash** [laravel-shield/shopify#1]
I need you to create docs for this driver https://github.com/laravel-shield/docs/issues/6
and tag v1 of this repo 😄

**Comment by TheAlexLichter** [comment]
Will do ☺️

**Comment by clarkeash** [comment]
Hey @manniL any update on this?

**Comment by TheAlexLichter** [comment]
Sorry, I was a little busy in the last weeks.

Will fulfill the task this week @clarkeash  :)

**Comment by clarkeash** [comment]
No problem, just wanted to check in 😄

**Comment by TheAlexLichter** [comment]
Done :)

https://github.com/laravel-shield/shopify/commit/732cf645cb6fd28428113f5cece7a5a5fe5eaf88
